"""
Pakistan Law Assistant – Local JSON Viewer (Stable v6.8)
Features:
✅ Auto Table of Contents when no section param is provided.
✅ Client-side search box for filtering sections by keywords.
✅ Compatible with URLs generated by query_law_pro.py (5002).
"""

from flask import Flask, request, render_template_string
import os, json

# --------------------------------------------------------------------
# Path to structured law JSONs
# --------------------------------------------------------------------
LAW_DIR = r"C:\wamp64\www\paklaw_codebase\pakistan_code_structured"

# Initialize Flask
app = Flask(__name__)

# --------------------------------------------------------------------
# HTML Template (dark UI + JS filtering)
# --------------------------------------------------------------------
PAGE_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ law_name }}</title>
<style>
    body { font-family:'Segoe UI',sans-serif; background:#0f0f0f; color:#f5f5f5; margin:40px; }
    h1 { color:#2fcf8f; margin-bottom:10px; }
    h2 { color:#ffc107; margin-top:20px; }
    .section { background:#1a1a1a; padding:15px; border-radius:10px; margin-bottom:20px; }
    a { color:#41b97a; text-decoration:none; }
    a:hover { text-decoration:underline; }
    .toc { background:#1b1b1b; padding:15px; border-radius:10px; }
    .back { display:inline-block; margin-top:20px; color:#41b97a; }
    input[type="text"] {
        width:100%; padding:10px; border-radius:8px; border:none;
        background:#222; color:#fff; font-size:16px; margin-bottom:15px;
    }
    li { line-height:1.6; }
</style>
<script>
function filterTOC() {
    let q = document.getElementById("searchBox").value.toLowerCase();
    let sections = document.querySelectorAll(".toc li");
    sections.forEach(li => {
        li.style.display = li.innerText.toLowerCase().includes(q) ? "" : "none";
    });
}
</script>
</head>
<body>
    <h1>{{ law_name.replace('_',' ') }}</h1>

    {% if toc %}
        <h2>📜 Table of Contents</h2>
        <input type="text" id="searchBox" onkeyup="filterTOC()" placeholder="🔍 Search within this Act...">
        <div class="toc">
            {% for ch in toc %}
                <h3>{{ ch.chapter_title }}</h3>
                <ul>
                {% for sec in ch.sections %}
                    <li>
                        <a href="/view?law={{ law_name }}&section={{ sec.section_no }}">
                            §{{ sec.section_no }} — {{ sec.section_title }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
    {% elif section_text %}
        <h2>Section {{ section_no }}</h2>
        <div class="section">{{ section_text }}</div>
    {% else %}
        <p>No section {{ section_no }} found in this law file.</p>
    {% endif %}

    <a class="back" href="javascript:history.back()">← Back</a>
</body>
</html>
"""

# --------------------------------------------------------------------
# Route to display a law file and section
# --------------------------------------------------------------------
@app.route("/view")
def view_law():
    law = request.args.get("law")
    section = request.args.get("section")

    if not law:
        return "⚠️ Missing 'law' parameter", 400

    # Find matching JSON file (case-insensitive)
    possible_files = [f for f in os.listdir(LAW_DIR)
                      if f.lower().startswith(law.lower()) and f.endswith(".json")]
    if not possible_files:
        return f"❌ No file found for law: {law}", 404

    path = os.path.join(LAW_DIR, possible_files[0])

    # Load JSON safely
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        return f"❌ Error reading file: {e}", 500

    # --- No section parameter → show TOC ---
    if not section:
        toc = []
        if "chapters" in data:
            for ch in data["chapters"]:
                toc.append({
                    "chapter_title": ch.get("chapter_title", "Untitled Chapter"),
                    "sections": ch.get("sections", [])
                })
        elif "sections" in data:
            toc.append({
                "chapter_title": data.get("law_name", law),
                "sections": data["sections"]
            })
        else:
            toc = None

        return render_template_string(
            PAGE_TEMPLATE,
            law_name=law,
            toc=toc,
            section_no=None,
            section_text=None
        )

    # --- Render a specific section ---
    section_text = None
    if "chapters" in data:
        for ch in data["chapters"]:
            for sec in ch.get("sections", []):
                if str(sec.get("section_no")) == str(section):
                    section_text = sec.get("body") or sec.get("text")
                    break
            if section_text:
                break
    elif "sections" in data:
        for sec in data["sections"]:
            if str(sec.get("section_no")) == str(section):
                section_text = sec.get("body") or sec.get("text")
                break

    return render_template_string(
        PAGE_TEMPLATE,
        law_name=law,
        section_no=section,
        section_text=section_text or "No text found for this section.",
        toc=None
    )

# --------------------------------------------------------------------
# Run local server
# --------------------------------------------------------------------
if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5002, debug=False)